### ISSUE TITLE
index was outside the bounds of the array

### ISSUE THREAD

**Issue by thexboxpc1** [Lewinator56/StormLoader#24]
when i try to install a mod i get the error 
"index was outside the bounds of the array.

kindly report this to the developer, your log is located in the install
directory.
the application will now quit"
i have done a fresh install of 1.1.1 but its still a problem

**Comment by Lewinator56** [comment]
Please provide a copy of the log. I can't do anything without it.

**Comment by thexboxpc1** [comment]
okay will get it now

**Comment by thexboxpc1** [comment]
19/01/2023 16:47:35: Running
19/01/2023 16:47:36: v1.0.12
19/01/2023 16:47:36: New version released
15/02/2023 13:41:41: Running
15/02/2023 13:41:42: v1.1
15/02/2023 13:41:42: New version released
19/03/2024 23:46:44: Running
19/03/2024 23:46:46: v1.1.1
19/03/2024 23:48:26: Index was outside the bounds of the array.
19/03/2024 23:48:26:    at StormLoader.MainWindow.AddModFromSLP(String path, String nameWithoutExt) in C:\Users\lewis\source\repos\StormLoader\StormLoader\StormLoader\MainWindow.xaml.cs:line 317
   at StormLoader.MainWindow.addModFromFile(String path, String nameWithoutExt, String ext, ModPack pack) in C:\Users\lewis\source\repos\StormLoader\StormLoader\StormLoader\MainWindow.xaml.cs:line 283
   at StormLoader.repository.RepoModListItem.<downloadMod>d__7.MoveNext() in C:\Users\lewis\source\repos\StormLoader\StormLoader\StormLoader\repository\RepoModListItem.xaml.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
19/03/2024 23:51:40: v1.1.1
19/03/2024 23:51:51: Index was outside the bounds of the array.
19/03/2024 23:51:51:    at StormLoader.MainWindow.AddModFromSLP(String path, String nameWithoutExt) in C:\Users\lewis\source\repos\StormLoader\StormLoader\StormLoader\MainWindow.xaml.cs:line 317
   at StormLoader.MainWindow.addModFromFile(String path, String nameWithoutExt, String ext, ModPack pack) in C:\Users\lewis\source\repos\StormLoader\StormLoader\StormLoader\MainWindow.xaml.cs:line 283
   at StormLoader.repository.RepoModListItem.<downloadMod>d__7.MoveNext() in C:\Users\lewis\source\repos\StormLoader\StormLoader\StormLoader\repository\RepoModListItem.xaml.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by Lewinator56** [comment]
Thank you, I will look into this tomorrow

**Comment by thexboxpc1** [comment]
ok

**Comment by thexboxpc1** [comment]
ok this is odd i just tried again and it mostly worked but eventually did give the error again and quit
